# swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- build

included: # paths to include during linting. `--path` is ignored if present.
- GiphyApp
- GiphyApp/Sources

disabled_rules: # rule identifiers to exclude from running
#  - cyclomatic_complexity
- trailing_whitespace
- force_cast
- line_length
- type_body_length

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
- explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_try:
severity: warning # explicitly
function_body_length: 100
file_length: 500

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)
